
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Antonio
 */
public class STATUS extends javax.swing.JFrame {

    /**
     * Creates new form STATUS
     */
    public STATUS() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(309, 340));
        setMinimumSize(new java.awt.Dimension(309, 340));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("Bin 1");
        jButton1.setToolTipText("");

        jButton2.setText("Bin 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Bin 3");

        jButton4.setText("Bin 4");

        jButton5.setText("Bin 5");

        jButton6.setText("Bin 6");

        jButton7.setText("Bin 7");

        jButton8.setText("Bin 8");

        jButton9.setText("Bin 9");

        jButton10.setText("Bin 10");

        jButton11.setText("Bin 11");

        jButton12.setText("Bin 12");

        jButton13.setText("Bin 13");

        jButton14.setText("Bin 14");

        jButton15.setText("Bin 15");

        jButton16.setText("Bin 16");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ScheduledExecutorService exec = Executors.newSingleThreadScheduledExecutor();
        exec.scheduleAtFixedRate(new Runnable() {
            @Override
            public void run() {
                refreshReading();
                System.out.println("printing");
            }
        }, 0, 2, TimeUnit.SECONDS);
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void refreshReading() {
        MysqlConnect mysqlConnect = new MysqlConnect();
        String sql = "SELECT * FROM `bioterio_01`";
        try {
            PreparedStatement statement = mysqlConnect.connect().prepareStatement(sql);
            ResultSet resultSet = statement.executeQuery("SELECT BinStatusBit from b01r01");
            ResultSetMetaData rsmd = resultSet.getMetaData();
            int columnsNumber = rsmd.getColumnCount();
            String Values;
            Values = "";
            while (resultSet.next()) {
                String columnValue = resultSet.getString(1);
                Values += columnValue;
            }

            if (Values.indexOf("1") >= 0) {
                jButton17.setBackground(Color.red);
                jButton17.setText("B01R01 ALLARMED");
            } else if (Values.indexOf("2") >= 0) {
                jButton17.setBackground(Color.yellow);
                jButton17.setText("B01R01 AKNOWLEDGE");
            } else {
                jButton17.setBackground(Color.green);
                jButton17.setText("B01R01 STATUS OK");
            }

            if (Character.getNumericValue(Values.charAt(0)) == 0) {
                jButton1.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(0)) == 1) {
                jButton1.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(0)) == 2) {
                jButton1.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(1)) == 0) {
                jButton2.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(1)) == 1) {
                jButton2.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(1)) == 2) {
                jButton2.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(1)) == 0) {
                jButton2.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(1)) == 1) {
                jButton2.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(1)) == 2) {
                jButton2.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(2)) == 0) {
                jButton3.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(2)) == 1) {
                jButton3.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(2)) == 2) {
                jButton3.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(3)) == 0) {
                jButton4.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(3)) == 1) {
                jButton4.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(3)) == 2) {
                jButton4.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(4)) == 0) {
                jButton5.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(4)) == 1) {
                jButton5.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(4)) == 2) {
                jButton5.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(5)) == 0) {
                jButton6.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(5)) == 1) {
                jButton6.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(5)) == 2) {
                jButton6.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(6)) == 0) {
                jButton7.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(6)) == 1) {
                jButton7.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(6)) == 2) {
                jButton7.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(7)) == 0) {
                jButton8.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(7)) == 1) {
                jButton8.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(7)) == 2) {
                jButton8.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(8)) == 0) {
                jButton9.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(8)) == 1) {
                jButton9.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(8)) == 2) {
                jButton9.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(9)) == 0) {
                jButton10.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(9)) == 1) {
                jButton10.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(9)) == 2) {
                jButton10.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(10)) == 0) {
                jButton11.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(10)) == 1) {
                jButton11.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(10)) == 2) {
                jButton11.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(11)) == 0) {
                jButton12.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(11)) == 1) {
                jButton12.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(11)) == 2) {
                jButton12.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(12)) == 0) {
                jButton13.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(12)) == 1) {
                jButton13.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(12)) == 2) {
                jButton13.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(13)) == 0) {
                jButton14.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(13)) == 1) {
                jButton14.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(13)) == 2) {
                jButton14.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(14)) == 0) {
                jButton15.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(14)) == 1) {
                jButton15.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(14)) == 2) {
                jButton15.setBackground(Color.yellow);
            }

            if (Character.getNumericValue(Values.charAt(15)) == 0) {
                jButton16.setBackground(Color.green);
            } else if (Character.getNumericValue(Values.charAt(15)) == 1) {
                jButton16.setBackground(Color.red);
            } else if (Character.getNumericValue(Values.charAt(15)) == 2) {
                jButton16.setBackground(Color.yellow);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            mysqlConnect.disconnect();
        }
    }

    public void delay(int seconds) {
        try {
            Thread.sleep(seconds * 1000);
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STATUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STATUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STATUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STATUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STATUS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
 // And From your main() method or any other method
}
